# Generated by Django 4.2.5 on 2023-09-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3)),
                ("decimal_places", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=18, max_digits=28),
                ),
                (
                    "payout_amount",
                    models.DecimalField(decimal_places=18, max_digits=28),
                ),
                ("payment_address", models.CharField(max_length=500, null=True)),
                ("payout_address", models.CharField(max_length=500, null=True)),
                ("expiry", models.DateTimeField()),
                ("complete", models.BooleanField(default=False)),
                (
                    "payment_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to="moneroex.asset",
                    ),
                ),
                (
                    "payout_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_orders",
                        to="moneroex.asset",
                    ),
                ),
            ],
        ),
    ]
