# Generated by Django 4.2.5 on 2023-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneroex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
    ]
