# Generated by Django 4.2.5 on 2023-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneroex", "0002_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="exchange_balance",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=28),
        ),
    ]
