# Generated by Django 4.2.5 on 2023-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneroex", "0003_asset_exchange_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="transaction_fee",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=28),
            preserve_default=False,
        ),
    ]
