# Generated by Django 4.2.5 on 2023-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneroex", "0004_asset_transaction_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="confirmations",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
